# Site settings
baseURL: "/"
languageCode: "fr-ca"
defaultContentLanguage: "fr"
title: "Le Pied"

buildFuture: true

#theme: "boilerplate"

# Copyright
copyright: "CC BY-NC-ND 4.0"

markup:
  goldmark:
    renderer:
      unsafe: true

params:

  # Metadata for search engines and social sharing
  author: "Le Pied"
  description: "La revue de création des étudiant·e·s en littératures de langue française de l'Université de Montréal."
  images:
  - "/feature.png"
  
  colophon: /colophon/

  # Links
  social_links:
  - text: "facebook"
    link: "https://www.facebook.com/revuelepied/"
  - text: "instagram"
    link: "https://www.instagram.com/revuelepied/"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

# Menu
menu:
  main:
    - identifier: revue
      title: revue
      url: /revue
      weight: 1
    - identifier: publications
      title: publications
      url: /publications
      weight: 2
    - identifier: evenements
      title: événements
      url: /evenements
      weight: 3
